from Graph import Graph

graph = Graph()
graph.create_vertex("v0")
graph.create_vertex("v1")
graph.create_vertex("v2")
graph.create_vertex("v3")
graph.create_vertex("v4")
graph.create_vertex("v5")
graph.add(1,"v0","v1")
graph.add(1,"v0","v5")
graph.add(1,"v2","v3")
graph.add(1,"v2","v1")
graph.add(1,"v3","v4")
graph.add(1,"v4","v1")
graph.add(1,"v4","v5")
graph.add(1,"v5","v1")
graph.add(1,"v5","v2")
graph.show()
print(graph)
